Use clang tidy to update codes for readability.
BlueQuartzSoftware/SIMPLView pull request #49
Opened 2018-11-09 01:49 UTC by imikejackson

clang-tidy was run with the following arguments:
-checks='-*,+readability-*,-readability-identifier-naming,modernize-use-equals-default'

Signed-off-by: Michael Jackson <mike.jackson@bluequartz.net>

2018-11-09 15:55 UTC, mmarineBlueQuartz approved these changes
This looks good.

2018-11-12 14:33 UTC, imikejackson commented
@mmarineBlueQuartz I started a fresh run of clang-tidy and removed some of the checks that were causing issues.

2018-11-12 14:34 UTC, imikejackson commented
@mmarineBlueQuartz I started a fresh run of clang-tidy and removed some of the checks that were causing issues.

2018-11-13 13:57 UTC, mmarineBlueQuartz commented on Source/SIMPLView/SIMPLViewApplication.cpp
> -    QDate currentDateToday = systemDate.currentDate();
systemDate is not used anywhere else and should be deleted to avoid confusion.

2018-11-13 14:03 UTC, mmarineBlueQuartz requested changes
QDate systemDate in SIMPLViewApplication (line 700) is not used anymore after the change.  To avoid confusion, the variable should be deleted with its only reference.

2018-11-13 14:30 UTC, imikejackson commented
Done.

2018-11-13 14:31 UTC, mmarineBlueQuartz approved these changes
Everything looks good now.

2018-11-14 18:29 UTC, merged