Add code generators for the MultiInputFile filter parameter
BlueQuartzSoftware/SIMPLView pull request #71
Opened 2021-02-04 03:16 UTC by imikejackson

Signed-off-by: Michael Jackson <mike.jackson@bluequartz.net>

2021-02-04 03:21 UTC, imikejackson commented
Related PRs

https://github.com/BlueQuartzSoftware/DREAM3D/pull/966
https://github.com/dream3d/DREAM3DReview/pull/40
https://github.com/BlueQuartzSoftware/SIMPL/pull/415

2021-02-04 03:22 UTC, imikejackson commented
https://github.com/BlueQuartzSoftware/DREAM3DCI/pull/53
https://github.com/BlueQuartzSoftware/DREAM3DCI/pull/52

2021-02-04 16:07 UTC, mmarineBlueQuartz approved these changes
It seems inconsistent for MultiInputFileWidgetCodeGenerator::New to be defined in the header when the other methods are not, but I don't see any other issues.

2021-02-08 19:26 UTC, JDuffeyBQ requested changes

2021-02-08 19:26 UTC, JDuffeyBQ commented on Source/DevHelper/CodeGenerators/MultiInputFileWidgetCodeGenerator.h
> +  virtual ~MultiInputFileWidgetCodeGenerator();
```suggestion
  ~MultiInputFileWidgetCodeGenerator() override;
```

2021-02-08 19:26 UTC, JDuffeyBQ commented on Source/DevHelper/CodeGenerators/MultiInputFileWidgetCodeGenerator.h
> +private:
```suggestion
```

2021-02-10 23:51 UTC, merged